algoritmo "semnome"
// Função :
// Autor :
// Data : 19/06/2025
// Seção de Declarações 
var
     a : real
     b : real
inicio
// Seção de Comandos
 escreva ("Entre com o primeiro número ")
 leia (a)
 
 escreva ("Entre com o segundo número ")
 leia (b)

 se a = b entao
  escreva ("os números são iguais lol")
 senao
    se a > b entao
      escreva ("o primeiro númeor é o maior")
    senao
      escreva ("o segundo número é maior")
    fimse
 fimse
 
fimalgoritmo
