algoritmo "semnome"
// Função :
// Autor :
// Data : 19/06/2025
// Seção de Declarações 
var
 salario : real
 
inicio
// Seção de Comandos 

escreva ("Entre com o valor do salário ")
leia (salario)
se salario = 50 entao
 escreval ("O salário digitado atendeu à condição! Vai ganhar aumento!")
 escreval ("Brincadeira kkk não é assim que funciona o mundo seu pobre")
fimse

escreva ("O salário foi processado! ")



fimalgoritmo
